version: '3.8'

services:
  node:
    build:
      context: ./
      dockerfile: ./docker/node/Dockerfile
    volumes:
      - "./:/var/www/html/app"
    working_dir: /var/www/html/app
    ports:
      - "5174:5174"
      - "3500:3500"
